// <auto-generated />
using System;
using HigherOrLower.API.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HigherOrLower.API.Migrations
{
    [DbContext(typeof(HigherLowerDbContext))]
    partial class HigherLowerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HigherOrLower.API.Models.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deck", (string)null);
                });

            modelBuilder.Entity("HigherOrLower.API.Models.Entities.HigherOrLowerGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeckId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("HigherOrLowerGames", (string)null);
                });

            modelBuilder.Entity("HigherOrLower.API.Models.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HigherOrLowerGameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HigherOrLowerGameId");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("HigherOrLower.API.Models.Entities.HigherOrLowerGame", b =>
                {
                    b.HasOne("HigherOrLower.API.Models.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("HigherOrLower.API.Models.Entities.Player", b =>
                {
                    b.HasOne("HigherOrLower.API.Models.Entities.HigherOrLowerGame", null)
                        .WithMany("Players")
                        .HasForeignKey("HigherOrLowerGameId");
                });

            modelBuilder.Entity("HigherOrLower.API.Models.Entities.HigherOrLowerGame", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
